**Run the following two cells before you begin.**

In [1]:
%autosave 10

Autosaving every 10 seconds


In [2]:
import pandas as pd
import numpy as np

______________________________________________________________________
**First, import your data set and define the sigmoid function.**
<details>
    <summary>Hint:</summary>
    The definition of the sigmoid is $f(x) = \frac{1}{1 + e^{-X}}$.
</details>

In [3]:
# Import the data set
df=pd.read_csv('cleaned_data.csv')
df

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  \
0      798fc410-45c1      20000    2          2         1   24      2      2   
1      8a8c8f3b-8eb4     120000    2          2         2   26     -1      2   
2      85698822-43f5      90000    2          2         2   34      0      0   
3      0737c11b-be42      50000    2          2         1   37      0      0   
4      3b7f77cc-dbc0      50000    1          2         1   57     -1      0   
...              ...        ...  ...        ...       ...  ...    ...    ...   
26659  ecff42d0-bdc6     220000    1          3         1   39      0      0   
26660  99d1fa0e-222b     150000    1          3         2   43     -1     -1   
26661  95cdd3e7-4f24      30000    1          2         2   37      4      3   
26662  00d03f02-04cd      80000    1          3         1   41      1     -1   
26663  15d69f9f-5ad3      50000    1          2         1   46      0      0   

       PAY_3  PAY_4  ...  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         -1     -1  ...         0         0         0         0   
1          0      0  ...      1000      1000         0      2000   
2          0      0  ...      1000      1000      1000      5000   
3          0      0  ...      1200      1100      1069      1000   
4         -1      0  ...     10000      9000       689       679   
...      ...    ...  ...       ...       ...       ...       ...   
26659      0      0  ...      5003      3047      5000      1000   
26660     -1     -1  ...      8998       129         0         0   
26661      2     -1  ...     22000      4200      2000      3100   
26662      0      0  ...      1178      1926     52964      1804   
26663      0      0  ...      1430      1000      1000      1000   

       default payment next month  EDUCATION_CAT  graduate school  \
0                               1     university                0   
1                               1     university                0   
2                               0     university                0   
3                               0     university                0   
4                               0     university                0   
...                           ...            ...              ...   
26659                           0    high school                0   
26660                           0    high school                0   
26661                           1     university                0   
26662                           1    high school                0   
26663                           1     university                0   

       high school  others  university  
0                0       0           1  
1                0       0           1  
2                0       0           1  
3                0       0           1  
4                0       0           1  
...            ...     ...         ...  
26659            1       0           0  
26660            1       0           0  
26661            0       0           1  
26662            1       0           0  
26663            0       0           1  

[26664 rows x 30 columns]

In [5]:
# Define the sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))


**Now, create a train/test split (80/20) with `PAY_1` and `LIMIT_BAL` as features and `default payment next month` as values. Use a random state of 24.**

In [10]:
# Create a train/test split
X=df[['PAY_1','LIMIT_BAL']]
Y=df['default payment next month']


In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=24)


______________________________________________________________________
**Next, import LogisticRegression, with the default options, but set the solver to `'liblinear'`.**

In [14]:
from sklearn.linear_model import LogisticRegression
my_lr=LogisticRegression(C=0.1,solver='liblinear')

______________________________________________________________________
**Now, train on the training data and obtain predicted classes, as well as class probabilities, using the testing data.**

In [15]:
# Fit the logistic regression model on training data
my_lr.fit(X_train,y_train)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
# Make predictions using `.predict()`
y_pred=my_lr.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [17]:
# Find class probabilities using `.predict_proba()`
class_pred=my_lr.predict_proba(X_test)
class_pred

array([[0.74826924, 0.25173076],
       [0.584297  , 0.415703  ],
       [0.79604453, 0.20395547],
       ...,
       [0.584297  , 0.415703  ],
       [0.82721498, 0.17278502],
       [0.66393435, 0.33606565]])

______________________________________________________________________
**Then, pull out the coefficients and intercept from the trained model and manually calculate predicted probabilities. You'll need to add a column of 1s to your features, to multiply by the intercept.**

In [18]:
# Add column of 1s to features
ones=np.ones((X_test.shape[0],1),dtype=int)
X_test=np.append(X_test,ones,axis=1)
X_test

array([[     2, 160000,      1],
       [     1,  50000,      1],
       [    -1, 200000,      1],
       ...,
       [    -1,  50000,      1],
       [     1, 230000,      1],
       [     2, 100000,      1]], dtype=int64)

In [19]:
# Get coefficients and intercepts from trained model
coeff=my_lr.coef_
intercept=my_lr.intercept_
coeff,intercept

(array([[ 8.27451187e-11, -6.80876727e-06]]), array([-6.57647457e-11]))

In [20]:
# Manually calculate predicted probabilities
coeffs=np.append(coeff,intercept)
coeffs

array([ 8.27451187e-11, -6.80876727e-06, -6.57647457e-11])

In [22]:
z=np.dot(coeffs,X_test.T)
print(len(z))
z

5333


array([-1.08940276, -0.34043836, -1.36175345, ..., -0.34043836,
       -1.56601647, -0.68087673])

In [24]:
preb_proba=sigmoid(z)
preb_proba

array([0.25173076, 0.415703  , 0.20395547, ..., 0.415703  , 0.17278502,
       0.33606565])

In [27]:
preb_prob=[]
for i in range(len(preb_proba)):
    temp=[]
    temp.append(1-preb_proba[i])
    temp.append(preb_proba[i])
    preb_prob.append(temp)
preb_prob

[[0.7482692412207597, 0.25173075877924034],
 [0.5842970026940478, 0.41570299730595217],
 [0.7960445320597681, 0.20395546794023192],
 [0.7960445320060308, 0.2039554679939692],
 [0.5842970026940478, 0.41570299730595217],
 [0.9206459615683938, 0.07935403843160614],
 [0.9206459615683938, 0.07935403843160614],
 [0.6639343456277687, 0.3360656543722313],
 [0.735228683914571, 0.2647713160854291],
 [0.760876414857184, 0.23912358514281598],
 [0.632905399536243, 0.3670946004637569],
 [0.5676699048051769, 0.4323300951948231],
 [0.7960445320463337, 0.20395546795366623],
 [0.5339913254281775, 0.4660086745718225],
 [0.7960445319522936, 0.20395546804770634],
 [0.8852008186486546, 0.11479918135134541],
 [0.6639343456277687, 0.3360656543722313],
 [0.6329053995554678, 0.36709460044453224],
 [0.8458207820248396, 0.1541792179751605],
 [0.6007343973421505, 0.3992656026578495],
 [0.6329053994977937, 0.3670946005022063],
 [0.930041796806994, 0.06995820319300608],
 [0.8272149830344913, 0.1727850169655088],
 [0

In [31]:
preb_prob=np.array(preb_prob)
preb_prob

array([[0.74826924, 0.25173076],
       [0.584297  , 0.415703  ],
       [0.79604453, 0.20395547],
       ...,
       [0.584297  , 0.415703  ],
       [0.82721498, 0.17278502],
       [0.66393435, 0.33606565]])

______________________________________________________________________
**Next, using a threshold of `0.5`, manually calculate predicted classes. Compare this to the class predictions output by scikit-learn.**

In [35]:
# Manually calculate predicted classes
classs=[]
for i in range(len(preb_prob)):
    if preb_prob[i][0]>0.5:
        classs.append(0.0)
    else:
        classs.append(1.0)
classs

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0

In [36]:
# Compare to scikit-learn's predicted classes
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

______________________________________________________________________
**Finally, calculate ROC AUC using both scikit-learn's predicted probabilities, and your manually predicted probabilities, and compare.**

In [41]:
# Use scikit-learn's predicted probabilities to calculate ROC AUC
from sklearn.metrics import roc_curve,roc_auc_score
roc_auc=roc_auc_score(y_test,class_pred[:,1])
roc_auc

0.627207450280691

In [45]:
# Use manually calculated predicted probabilities to calculate ROC AUC
ruc_man=roc_auc_score(y_test,preb_prob[:,1])
ruc_man

0.627207450280691